let money = 1500;
let income = 'freelance';
let addExpenses = 'taxi, ethernet, communal';
let deposit = true;
let mission = 1000000;
let period = 7;
console.log(typeof money);
console.log(typeof income);
console.log(typeof deposit);
console.log(addExpenses.length);
console.log('The period is', period, 'mounth and purpose make', mission, 'dollars');
console.log(addExpenses.toLowerCase);
console.log(addExpenses.split(', '));
let budgetDay = money/30;
console.log('budgetDay: ', budgetDay);
